# Generated by Django 5.0.1 on 2024-07-25 14:29

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Hobbies',
            new_name='Hobby',
        ),
        migrations.AlterModelOptions(
            name='hobby',
            options={'verbose_name': 'Hobby', 'verbose_name_plural': 'Hobbies'},
        ),
        migrations.AlterModelOptions(
            name='interest',
            options={'verbose_name': 'Interest', 'verbose_name_plural': 'Interests'},
        ),
        migrations.RenameField(
            model_name='hobby',
            old_name='hobbies',
            new_name='hobby',
        ),
        migrations.AlterField(
            model_name='custommyuser',
            name='country',
            field=models.CharField(choices=[('america', 'AMERICA'), ('europe', 'EUROPE'), ('india', 'INDIA'), ('canada', 'CANADA'), ('middle east', 'MIDDLE EAST')], max_length=50),
        ),
        migrations.CreateModel(
            name='JobProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('jobprofile', models.CharField(blank=True, choices=[('jobseeker', 'JOB SEEKER'), ('employer', 'EMPLOYER')], max_length=100, null=True)),
                ('expertise', models.CharField(blank=True, choices=[('fresher', 'FRESHER'), ('expert', 'EXPERT')], max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_users.company')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_users.jobtitle')),
            ],
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('salary_package', models.CharField(max_length=100)),
                ('vacancies', models.PositiveIntegerField()),
                ('job_type', models.CharField(choices=[('part time', 'PART TIME'), ('temporary', 'TEMPORARY'), ('full time', 'FULL TIME'), ('contract', 'CONTRACT')], max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('rather not say', 'RATHER NOT SAY')], max_length=15)),
                ('job_description', ckeditor.fields.RichTextField()),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_users.company')),
                ('job_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_users.jobcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_users.jobtitle')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_status', models.BooleanField(default=False)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_users.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_users.jobprofile')),
            ],
        ),
    ]
