# Generated by Django 5.0.1 on 2024-07-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0002_company_jobcategory_jobtitle_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommyuser',
            name='country',
            field=models.CharField(choices=[('india', 'INDIA'), ('america', 'AMERICA'), ('europe', 'EUROPE'), ('middle east', 'MIDDLE EAST'), ('canada', 'CANADA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='custommyuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='user/profile_pics/Default_profile.png', null=True, upload_to='users/profile_pics/'),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='job_type',
            field=models.CharField(choices=[('full time', 'FULL TIME'), ('contract', 'CONTRACT'), ('part time', 'PART TIME'), ('temporary', 'TEMPORARY')], max_length=100),
        ),
    ]
