# Generated by Django 5.0.1 on 2024-07-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0003_alter_custommyuser_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='job_type',
            field=models.CharField(choices=[('temporary', 'TEMPORARY'), ('full time', 'FULL TIME'), ('part time', 'PART TIME'), ('contract', 'CONTRACT')], max_length=100),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='expertise',
            field=models.CharField(blank=True, choices=[('expert', 'EXPERT'), ('fresher', 'FRESHER')], max_length=100, null=True),
        ),
    ]
