# Generated by Django 5.0.1 on 2024-07-30 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0004_skills_alter_jobdescription_job_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='job_type',
            field=models.CharField(choices=[('part time', 'PART TIME'), ('contract', 'CONTRACT'), ('full time', 'FULL TIME'), ('temporary', 'TEMPORARY')], max_length=100),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='expertise',
            field=models.CharField(blank=True, choices=[('fresher', 'FRESHER'), ('expert', 'EXPERT')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='jobprofile',
            field=models.CharField(blank=True, choices=[('employer', 'EMPLOYER'), ('jobseeker', 'JOB SEEKER')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=15)),
                ('qualification', models.CharField(max_length=100)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_users.jobdescription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
