# Generated by Django 5.0.1 on 2024-07-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0005_alter_skills_options_alter_jobdescription_job_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='job_type',
            field=models.CharField(choices=[('full time', 'FULL TIME'), ('part time', 'PART TIME'), ('temporary', 'TEMPORARY'), ('contract', 'CONTRACT')], max_length=100),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='expertise',
            field=models.CharField(blank=True, choices=[('expert', 'EXPERT'), ('fresher', 'FRESHER')], max_length=100, null=True),
        ),
    ]
