# Generated by Django 5.0.1 on 2024-07-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0006_alter_jobdescription_job_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='job_type',
            field=models.CharField(choices=[('contract', 'CONTRACT'), ('part time', 'PART TIME'), ('full time', 'FULL TIME'), ('temporary', 'TEMPORARY')], max_length=100),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='expertise',
            field=models.CharField(blank=True, choices=[('fresher', 'FRESHER'), ('expert', 'EXPERT')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='jobprofile',
            field=models.CharField(blank=True, choices=[('jobseeker', 'JOB SEEKER'), ('employer', 'EMPLOYER')], max_length=100, null=True),
        ),
    ]
