# Generated by Django 5.0.1 on 2024-07-31 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0007_alter_jobdescription_job_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='applied_at',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='email',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='qualification',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='Designation',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='last_working_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='quit_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='salary',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='job_type',
            field=models.CharField(choices=[('part time', 'PART TIME'), ('temporary', 'TEMPORARY'), ('contract', 'CONTRACT'), ('full time', 'FULL TIME')], max_length=100),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='expertise',
            field=models.CharField(blank=True, choices=[('expert', 'EXPERT'), ('fresher', 'FRESHER')], max_length=100, null=True),
        ),
    ]
