# Generated by Django 5.0.1 on 2024-07-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0008_remove_jobapplication_applied_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='Designation',
            new_name='designation',
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='job_type',
            field=models.CharField(choices=[('temporary', 'TEMPORARY'), ('contract', 'CONTRACT'), ('part time', 'PART TIME'), ('full time', 'FULL TIME')], max_length=100),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='expertise',
            field=models.CharField(blank=True, choices=[('fresher', 'FRESHER'), ('expert', 'EXPERT')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='jobprofile',
            field=models.CharField(blank=True, choices=[('employer', 'EMPLOYER'), ('jobseeker', 'JOB SEEKER')], max_length=100, null=True),
        ),
    ]
